"""empty message

Revision ID: 415760b41c4a
Revises: 98a3fdb4ae20
Create Date: 2023-01-28 15:21:41.404667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415760b41c4a'
down_revision = '98a3fdb4ae20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    # ### end Alembic commands ###
